`timescale 1ns / 1ps

module tb_conv1_array;

    reg clk;
    reg reset;
    
    // Weight delivery
    reg [575:0] conv1_weights;
    
    // Testbench ROMs
    reg [15:0] image_rom [0:399];
    reg [15:0] weights_flat [0:35]; // 4 channels x 9 weights
    
    // Expected Output ROM: 400 positions x 4 channels = 1600 expected values
    reg [15:0] expected_out_flat [0:1599];
    
    wire [8:0] pixel_addr;
    reg signed [15:0] pixel_in;
    
    wire signed [15:0] out_ch0;
    wire signed [15:0] out_ch1;
    wire signed [15:0] out_ch2;
    wire signed [15:0] out_ch3;
    wire valid_out;
    wire done;

    // Combinational RAM read (Interface Contract)
    always @(*) begin
        if (pixel_addr < 400) begin
            pixel_in = image_rom[pixel_addr];
        end else begin
            pixel_in = 16'd0;
        end
    end

    conv1_array uut (
        .clk(clk),
        .reset(reset),
        .conv1_weights(conv1_weights),
        .pixel_addr(pixel_addr),
        .pixel_in(pixel_in),
        .out_ch0(out_ch0),
        .out_ch1(out_ch1),
        .out_ch2(out_ch2),
        .out_ch3(out_ch3),
        .valid_out(valid_out),
        .done(done)
    );

    always #5 clk = ~clk;

    integer i;
    integer out_count = 0;
    integer match_count = 0;
    integer failed = 0;

    initial begin
        $dumpfile("tb_conv1_array.vcd");
        $dumpvars(0, tb_conv1_array);

        // Load data from text files generated by golden model
        $readmemh("../python_golden_model/test_image_q7_8.txt", image_rom);
        $readmemh("../python_golden_model/weights_q7_8.txt", weights_flat);
        $readmemh("../python_golden_model/expected_conv1_out.txt", expected_out_flat);
        
        // Pack weights into the flat 576-bit bus
        // ChX is offset by (X * 144). Tap Y is offset by (Y * 16) within the channel block.
        for (i = 0; i < 36; i = i + 1) begin
            conv1_weights[(i * 16) +: 16] = weights_flat[i];
        end

        clk = 0;
        reset = 1;
        
        #20;
        reset = 0;
        
        // Wait until module reports done
        wait(done == 1'b1);
        
        #20;
        if (out_count == 400 && match_count == 1600 && failed == 0) begin
            $display("ALL TESTS PASSED: %0d/1600 outputs matched.", match_count);
        end else begin
            $display("FAILED: Expected 400 valid assertions, got %0d. Expected 1600 matches, got %0d. Total failures: %0d", out_count, match_count, failed);
        end

        $finish;
    end

    // Verify outputs dynamically as they stream out
    always @(posedge clk) begin
        if (valid_out && !reset) begin
            // Expected indices for this window's 4 channels
            // The python model output is written as Ch0, Ch1, Ch2, Ch3 sequentially for each window position
            begin : check_block
                reg signed [15:0] exp0, exp1, exp2, exp3;
                exp0 = expected_out_flat[out_count * 4 + 0];
                exp1 = expected_out_flat[out_count * 4 + 1];
                exp2 = expected_out_flat[out_count * 4 + 2];
                exp3 = expected_out_flat[out_count * 4 + 3];
                
                if (out_ch0 !== exp0) begin
                    $display("FAIL at window %0d Ch0: Expected %d, Got %d", out_count, exp0, out_ch0);
                    failed = failed + 1;
                end else match_count = match_count + 1;

                if (out_ch1 !== exp1) begin
                    $display("FAIL at window %0d Ch1: Expected %d, Got %d", out_count, exp1, out_ch1);
                    failed = failed + 1;
                end else match_count = match_count + 1;

                if (out_ch2 !== exp2) begin
                    $display("FAIL at window %0d Ch2: Expected %d, Got %d", out_count, exp2, out_ch2);
                    failed = failed + 1;
                end else match_count = match_count + 1;

                if (out_ch3 !== exp3) begin
                    $display("FAIL at window %0d Ch3: Expected %d, Got %d", out_count, exp3, out_ch3);
                    failed = failed + 1;
                end else match_count = match_count + 1;
            end
            
            out_count = out_count + 1;
        end
    end

endmodule
